//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fatih_Karameşe_BitirmeTezi_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class İslem
    {
        public int Id { get; set; }
        public Nullable<int> İslemNo { get; set; }
    }
}
