//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fatih_Karameşe_BitirmeTezi_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanıvılar
    {
        public int Id { get; set; }
        public string AdSoyad { get; set; }
        public string Telefon { get; set; }
        public string EPosta { get; set; }
        public string Kullanıcı { get; set; }
        public string Sifre { get; set; }
        public Nullable<bool> Satis { get; set; }
        public Nullable<bool> Rapor { get; set; }
        public Nullable<bool> stok { get; set; }
        public Nullable<bool> ürüngiris { get; set; }
        public Nullable<bool> kullanıcılar { get; set; }
        public Nullable<bool> fiyatgüncelle { get; set; }
        public Nullable<bool> yedekleme { get; set; }
    }
}
